export const FETCH_REPORTS_RETRIEVE = 'FETCH_REPORTS_RETRIEVE';
export const FETCH_REPORTS_SUCCESS = 'FETCH_REPORTS_SUCCESS';
export const FETCH_REPORTS_FAILURE = 'FETCH_REPORTS_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const NAVBAR_TITLE = 'NAVBAR_TITLE';